### ISSUE TITLE
Fix File directory 

### ISSUE THREAD

**Issue by braedeningersoll** [braedeningersoll/haab_movies#1]
File directory could be made cleaner

**Comment by braedeningersoll** [comment]
Hey all, please let me know when you finish your projects and push to the source Tree tonight so I can fix the file directory system.

**Comment by braedeningersoll** [comment]
Hey all, please let me know when you finish your projects and push to the source Tree tonight so I can fix the file directory system.

**Comment by angeladolecheck** [comment]
i have uploaded my final pages.

**Comment by adrbrewer** [comment]
I have finished all of my pages.
