### ISSUE TITLE
Rubric item- Text stylizing

### ISSUE THREAD

**Issue by braedeningersoll** [braedeningersoll/haab_movies#10]
Hey guys there is one requirement on the rubric that I overlooked but noticed on further review that we need to utilize the stylizing effects on text in our pages. I.e. italics, bolding, headers, etc.

We have lots of headers but we could easily add italics to the site by making an movie titles that are not inside of tables or headers italicized. 

Just food for thought but I think this is an edit I will make to my pages.

**Comment by angeladolecheck** [comment]
Sounds great thanks

**Comment by braedeningersoll** [comment]
I totally forgot about the bolding we already have on the staring, run time, and MPAA rating so this is actually a lot less of an issue than I thought, sorry about that.
