### ISSUE TITLE
Properly Formatted Titles- All pages

### ISSUE THREAD

**Issue by braedeningersoll** [braedeningersoll/haab_movies#2]
In order for the index table of contents to be valid and not error/ warning message in the command prompt we all need to have properly formatted Titles at the top of all our pages.

I.e:
"This is a title"
"--------------"

or

"This is a title"
"========"

or

"This is a title"
"~~~~~~~~"

Ignore the quotations I had to include them to display this text inside the window otherwise it will do the output formatting here on Github.

**Comment by angeladolecheck** [comment]
I am no longer getting any title errors, I believe mine are fixed

**Comment by braedeningersoll** [comment]
From my last make html command (last done at 12:30am -12-7-17) the pages: location & videogames are the only two that still require this.
