### ISSUE TITLE
Second Round of Reviews

### ISSUE THREAD

**Issue by holly-tran** [braedeningersoll/haab_movies#6]
Angela reviews Braeden
Holly reviews Angela
Addie reviews Holly
Braeden reviews Addie

**Comment by braedeningersoll** [comment]
Be sure that when you go to make comments you click into their most recent update to the github!

**Comment by angeladolecheck** [comment]
I have completed my second review

**Comment by holly-tran** [comment]
I finished this as well.

**Comment by braedeningersoll** [comment]
Finished my review.

**Comment by braedeningersoll** [comment]
Finished my reviews

**Comment by adrbrewer** [comment]
I have done my reviews.
